export * from './schemas/primitives.js'
export * from './schemas/shared.js'
export * from './schemas/validation.js'
export * from './math/range.js'
export * from './math/ticks.js'
export * from './math/geometry.js'
export * from './animation/easing.js'
export * from './animation/timeline.js'
export * from './animation/scheduler.js'
export * from './render/context.js'
export * from './theme/tokens.js'
export * from './extensions/interfaces.js'
export * from './contracts/gauge-contract.js'
export * from './compass/schema.js'
export * from './compass/renderer.js'
export * from './linear/schema.js'
export * from './linear/renderer.js'
export * from './radial/schema.js'
export * from './radial/renderer.js'

export type { RadialGaugeConfig } from './radial/schema.js'
export type { LinearGaugeConfig } from './linear/schema.js'
export type { CompassGaugeConfig } from './compass/schema.js'

export const version = '0.0.0'
